on: [ push ]

name: AzureARMDeploy

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 

    - name: checking source code
      uses: actions/checkout@v2

    - name: deploying the ARM template
      uses: azure/CLI@v1   
      with:
        inlineScript: |
          az deployment group create \
          --name AvailSetdeploy \
          --resource-group cloud-shell-storage-centralindia \
          --template-file arm_deploy.json
